name: CIHUY

on:
  push:
    branches: [ "cihuy" ]

  workflow_dispatch:

jobs:
  huy_build:
    runs-on: ubuntu-latest

    steps:
      - name: Huy remote exec ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY }}" >  ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          
